# Generated by Django 3.1.7 on 2021-03-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hotel',
            new_name='temp',
        ),
    ]
