# Generated by Django 3.1.7 on 2021-03-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='name',
            new_name='username',
        ),
    ]
