# Generated by Django 3.1.7 on 2021-03-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210322_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
