# Generated by Django 3.1.7 on 2021-03-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210322_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('decs', models.TextField()),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
                ('image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
