# Generated by Django 3.1.7 on 2021-03-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_roomtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
